title: Hektor Buqaj
logo: /assets/img/PFP_circular.png
description: Data Science in Engineering @ Umich 
# show_downloads: true
theme: jekyll-theme-minimal
resume_file: assets/downloads/Buqaj_Resume.pdf